// const data = [
//   {
//     id: 1,
//     fullName: 'Yuri Lys',
//     position: 'Team Leader',
//     photo: `./${}`,
//     linkedIn: '',
//     gitHub: '',
//   },
//   {
//     id: 2,
//     fullName: 'Alina Polischuk',
//     position: 'Scrum master',
//     photo: `./${}`,
//     linkedIn: '',
//     gitHub: '',
//   },
//   {
//     id: 3,
//     fullName: '',
//     position: '',
//     photo: `./${}`,
//     linkedIn: '',
//     gitHub: '',
//   },
//   {
//     id: 4,
//     fullName: '',
//     position: '',
//     photo: `./${}`,
//     linkedIn:
//       '',
//     gitHub: '',
//   },
//   {
//     id: 5,
//     fullName: '',
//     position: '',
//     photo: `./${}`,
//     linkedIn: '',
//     gitHub: '',
//   },
//   {
//     id: 6,
//     fullName: '',
//     position: '',
//     photo: `./${}`,
//     linkedIn: '#',
//     gitHub: '',
//   },
//   {
//     id: 7,
//     fullName: '',
//     position: '',
//     photo: `./${}`,
//     linkedIn: '',
//     gitHub: '',
//   },
//   {
//     id: 8,
//     fullName: ' ',
//     position: '',
//     photo: `./${}`,
//     linkedIn: '',
//     gitHub: '',
//     },
//    {
//     id: 9,
//     fullName: ' ',
//     position: '',
//     photo: `./${}`,
//     linkedIn: '',
//     gitHub: '',
//   }
// ];
// export default data;
